syntax = "proto2";

package apollo.planning;

message FollowModelConfig {
    optional bool enable_idm = 1 [default = false];
    optional double unit_t = 2 [default = 1.0];
    optional double search_lane_distance = 3 [default = 5.0];   
    optional int32 search_lane_depth = 4 [default = 2];         // 用于 cipv 判断当前 lane 下 search_lane_depth 个lane 都在前方
    required double expect_speed = 5;                           // 期望速度     unit: m/s
    required double delta_acceleration = 6;                     // 加速度指数
    required double max_acceleration = 7;                       // 最大加速度   unit: m/s²
    required double comfortable_deceleration = 8;               // 舒适减速度   unit: m/s²
    required double saft_distance = 9;                          // 安全时距    unit: s
    required double min_saft_distance = 10;                     // 最小安全距离 unit: s
}