syntax = "proto2";

package apollo.planning;


message ModelParameter{
    // all model
    required double min_gap = 1;            // 最小安全距离 (m) >= 0
    required double accel = 2;              // 加速度能力 (m/s²) >= 0
    required double decel = 3;              // 减速度能力 (m/s²) >= 0
    required double emergency_decel = 4;    // 紧急情况减速度能力 (m/s²) >= decel
    required double tau = 5;                // 安全时距 (s)  >= 0
    optional double expect_speed = 6;       // 期望速度 (m/s), default： 当前道路的限速

    // IDM,EIDM
    optional double delta = 20 [ default = 4 ];      // 加速度指数
    optional double stepping = 21 [default = 0.25];  // 计算跟随速度时的内部步长 (s) >= 0
    // IDMM
    optional double adapt_factor = 22 [ default = 1.8 ];    // 适应因子，对过去交通状况变化的敏感程度 >= 0
    optional double adapt_time = 23 [default = 600];        // 驾驶员行为恢复正常（从适应状态缓慢回归）的时间窗口 (s) >= 0

}


message CarFollowModel{
    enum Type{
        CUSTOM = 0; // 自定义模型
        IDM = 1;
        IDMM = 2;
        EIDM = 3;
    }

    required Type type = 1;
    // 自定义模型时需填写以下参数
    optional string name = 2;
    optional string model_path = 3;     // 自定义模型的 .so 路径
    optional string config_path = 4;    // 自定义模型的配置路径
}

message FollowModelConfig {
    optional bool enable_follow_mode = 1 [default = false];
    optional double unit_t = 2 [default = 1.0];
    optional double search_lane_distance = 3 [default = 5.0];   
    optional int32 search_lane_depth = 4 [default = 2];         // 用于 cipv 判断当前 lane 下 search_lane_depth 个lane 都在前方
    required CarFollowModel model = 5;                          // 跟车模型
    required ModelParameter model_param = 6;
    optional bool enable_debug_output = 7 [default = false];
}