syntax = "proto2";

package apollo.planning;

message IDMModelTaskConfig {
    optional double expect_speed = 1;                // 期望速度     unit: m/s
    optional double delta_acceleration = 2;          // 加速度指数
    optional double max_acceleration = 3;            // 最大加速度   unit: m/s²
    optional double comfortable_deceleration = 4;    // 舒适减速度   unit: m/s²
    optional double saft_distance = 5;               // 安全时距     unit: s
    optional double min_saft_distance = 6;           // 最小安全距离 unit: s
}